# ASSIGNMENT 2

In [41]:
import numpy as np

In [2]:
#Create an array of 10 zeros

arr=np.zeros(10)

In [3]:
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
#Create an array of 10 ones

arr=np.ones(10)

In [5]:
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
#Create an array of 10 fives

arr=np.ones(10)*5

In [7]:
arr

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [8]:
#Create an array of the integers from 10 to 50

arr=np.array(range(10,51))

In [9]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [12]:
#Create an array of all the even integers from 10 to 50

arr=np.arange(10,51,2)

In [13]:
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [14]:
#Create a 3x3 matrix with values ranging from 0 to 8

arr=np.arange(0,9)

In [15]:
arr.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
#Create a 3x3 identity matrix

arr=np.identity(3)

In [19]:
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
#Use NumPy to generate a random number between 0 and 1

np.random.rand(1)

array([0.65159604])

In [23]:
#Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

np.random.rand(25)

array([0.31616425, 0.44220338, 0.76854998, 0.75386946, 0.56826761,
       0.95139226, 0.08819701, 0.27725101, 0.41902193, 0.39934863,
       0.32324831, 0.64391593, 0.5982932 , 0.47733494, 0.02928879,
       0.74629925, 0.03293631, 0.88307352, 0.89022475, 0.18350702,
       0.59838509, 0.94419291, 0.7347233 , 0.15515885, 0.38618986])

In [26]:
#Create the following matrix:

arr=np.arange(0.01,1.01,0.01).reshape(10,10)

In [27]:
arr

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [28]:
#Create an array of 20 linearly spaced points between 0 and 1:

arr=np.linspace(0,1,20)

In [29]:
arr

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

# Numpy Indexing and Selection

In [30]:
arr=np.arange(1,26).reshape(5,5)

In [31]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [32]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [33]:
arr[3,4]

20

In [34]:
arr[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [35]:
arr[4]

array([21, 22, 23, 24, 25])

# Now do the following

In [36]:
arr.sum()

325

In [37]:
arr.std()

7.211102550927978

In [38]:
arr[:,4:]

array([[ 5],
       [10],
       [15],
       [20],
       [25]])

In [39]:
arr=np.linspace(55,75,5,dtype=int)

In [40]:
arr

array([55, 60, 65, 70, 75])